exclude: ["Makefile*", "LICENSE", "README*.md", "*.scad", "common/*", "*/Makefile", "*/deps", "*/anim-*.png", "Gemfile", "Gemfile.lock"]
domain: woodworking-plans.beerriot.com
url: https://woodworking-plans.beerriot.com
email_suffix: woodworking
remote_theme: beerriot/purecss-theme
title: "BeerRiot"
subtitle: "Woodworking Plans"
repo_url: https://github.com/beerriot/woodworking-plans/
repo_link_in_menu: true