# Paths use during build. Multiple Makefiles may need to agree on
# these, so they are consolidated here.

OPENSCAD=$(shell which openscad)

ifeq (${OPENSCAD},)
     $(error "Command openscad not found. Set OPENSCAD in Makefile.paths, or set PATH to include openscad.")
endif
