# Paths use during build. Multiple Makefiles may need to agree on
# these, so they are consolidated here.

OPENSCAD=$(shell which openscad)

ifeq (${OPENSCAD},)
     $(error "Command openscad not found. Set OPENSCAD in Makefile.paths, or set PATH to include openscad.")
endif


# These should all end in /, or the cp in the top-level release target
# won't work right.
RELEASE_DIR=release/
BUILD_DIR=build/
DEPS_DIR=deps/

COMMIT_HASH=$(shell git log -1 --pretty="format:%h")
